<?php

namespace ContainerO4xDgOB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iSuiQQo.App\Entity\Employer' shared service.
     *
     * @return \App\Entity\Employer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iSuiQQo": it references class "App\\Entity\\Employer" but no such service exists.');
    }
}
