<?php

namespace ContainerQPRHOXT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ISuiQQoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iSuiQQo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iSuiQQo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'employer' => ['privates', '.errored..service_locator.iSuiQQo.App\\Entity\\Employer', NULL, 'Cannot autowire service ".service_locator.iSuiQQo": it references class "App\\Entity\\Employer" but no such service exists.'],
        ], [
            'employer' => 'App\\Entity\\Employer',
        ]);
    }
}
