<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQxKpWg\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQxKpWg/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHQxKpWg.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHQxKpWg\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerHQxKpWg\App_KernelTestDebugContainer([
    'container.build_hash' => 'HQxKpWg',
    'container.build_id' => '3eab76e4',
    'container.build_time' => 1620141096,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQxKpWg');
