<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'client_index' => [[], ['_controller' => 'App\\Controller\\ClientController::index'], [], [['text', '/client/']], [], []],
    'client_new' => [[], ['_controller' => 'App\\Controller\\ClientController::new'], [], [['text', '/client/new']], [], []],
    'client_show' => [['id'], ['_controller' => 'App\\Controller\\ClientController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], []],
    'client_edit' => [['id'], ['_controller' => 'App\\Controller\\ClientController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], []],
    'client_delete' => [['id'], ['_controller' => 'App\\Controller\\ClientController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/']], [], []],
    'employer_index' => [[], ['_controller' => 'App\\Controller\\EmployerController::index'], [], [['text', '/employer/']], [], []],
    'employer_new' => [[], ['_controller' => 'App\\Controller\\EmployerController::new'], [], [['text', '/employer/new']], [], []],
    'employer_show' => [['id'], ['_controller' => 'App\\Controller\\EmployerController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/employer']], [], []],
    'employer_edit' => [['id'], ['_controller' => 'App\\Controller\\EmployerController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/employer']], [], []],
    'employer_delete' => [['id'], ['_controller' => 'App\\Controller\\EmployerController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/employer']], [], []],
];
