<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZxBhT8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZxBhT8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZxBhT8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZxBhT8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZxBhT8\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZxBhT8',
    'container.build_id' => '6e5dea9c',
    'container.build_time' => 1620154075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZxBhT8');
